
export const FETCH_ARTS_REQUEST = "FETCH_ARTS_REQUEST";
export const FETCH_ARTS_SUCCESS = "FETCH_ARTS_SUCCESS";
export const FETCH_ARTS_FAILURE = "FETCH_ARTS_FAILURE";

export const GET_CART_ITEMS = 'GET_CART_ITEMS';
// export const DELETE_CART_ITEM = 'DELETE_CART_ITEM';

