export const FETCH_ARTS_REQUEST = "FETCH_ARTS_REQUEST";
export const FETCH_ARTS_SUCCESS = "FETCH_ARTS_SUCCESS";
export const FETCH_ARTS_FAILURE = "FETCH_ARTS_FAILURE";

export const FETCH_ALLARTS_SUCCESS = "FETCH_ALLARTS_SUCCESS";
export const UPDATE_ART_SUCCESS = "UPDATE_ART_SUCCESS";
export const UPDATE_ART_FAILURE = "UPDATE_ART_FAILURE";
export const POST_ART_REQUEST = "POST_ART_REQUEST";
export const POST_ART_SUCCESS = "POST_ART_SUCCESS";
export const POST_ART_FAILURE = "POST_ART_FAILURE";

export const DELETE_ART_REQUEST = "DELETE_ART_REQUEST";
export const DELETE_ART_SUCCESS = "DELETE_ART_SUCCESS";
export const DELETE_ART_FAILURE = "DELETE_ART_FAILURE";

export const GET_CART_ITEMS = "GET_CART_ITEMS";
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM';
export const GET_FAV_ITEMS = "GET_CART_ITEMS";
export const DELETE_FAV_ITEM = 'DELETE_CART_ITEM';
